//
//  AppDelegate.h
//  Electricity Recorder
//
//  Created by ydhuang on 15-9-16.
//  Copyright (c) 2015年 chenzw. All rights reserved.
//

#import <Cocoa/Cocoa.h>
#import "CSVLog.h"
#import "Config.h"
#import "BoardController.h"
#import "SerialNameScan.h"

@interface AppDelegate : NSObject <NSApplicationDelegate,NSWindowDelegate>
{
    NSMutableArray* m_PortNameArray;
    NSArray* m_SavePortName;
    BoardController* m_Board;
    CSVLog* m_Log;
    SerialNameScan	*scanPort;
    NSInteger TimeCount;
    NSInteger PortIndex;
    BOOL START;
    IBOutlet NSButton* btnStart;
    IBOutlet NSTextField* BoardNum;
    IBOutlet NSTextField* BoardIndex;
    IBOutlet NSTabView* m_Tab;
    
    IBOutlet NSTextField* Board1Port1Color;
    IBOutlet NSTextField* Board1Port2Color;
    IBOutlet NSTextField* Board1Port3Color;
    IBOutlet NSTextField* Board1Port4Color;
    IBOutlet NSTextField* Board1Port5Color;
    IBOutlet NSTextField* Board1Port6Color;
    IBOutlet NSTextField* Board1Port7Color;
    IBOutlet NSTextField* Board1Port8Color;
    IBOutlet NSTextField* Board2Port1Color;
    IBOutlet NSTextField* Board2Port2Color;
    IBOutlet NSTextField* Board2Port3Color;
    IBOutlet NSTextField* Board2Port4Color;
    IBOutlet NSTextField* Board2Port5Color;
    IBOutlet NSTextField* Board2Port6Color;
    IBOutlet NSTextField* Board2Port7Color;
    IBOutlet NSTextField* Board2Port8Color;
    IBOutlet NSTextField* Board3Port1Color;
    IBOutlet NSTextField* Board3Port2Color;
    IBOutlet NSTextField* Board3Port3Color;
    IBOutlet NSTextField* Board3Port4Color;
    IBOutlet NSTextField* Board3Port5Color;
    IBOutlet NSTextField* Board3Port6Color;
    IBOutlet NSTextField* Board3Port7Color;
    IBOutlet NSTextField* Board3Port8Color;
    IBOutlet NSTextField* Board4Port1Color;
    IBOutlet NSTextField* Board4Port2Color;
    IBOutlet NSTextField* Board4Port3Color;
    IBOutlet NSTextField* Board4Port4Color;
    IBOutlet NSTextField* Board4Port5Color;
    IBOutlet NSTextField* Board4Port6Color;
    IBOutlet NSTextField* Board4Port7Color;
    IBOutlet NSTextField* Board4Port8Color;
    IBOutlet NSTextField* Board5Port1Color;
    IBOutlet NSTextField* Board5Port2Color;
    IBOutlet NSTextField* Board5Port3Color;
    IBOutlet NSTextField* Board5Port4Color;
    IBOutlet NSTextField* Board5Port5Color;
    IBOutlet NSTextField* Board5Port6Color;
    IBOutlet NSTextField* Board5Port7Color;
    IBOutlet NSTextField* Board5Port8Color;
    IBOutlet NSTextField* Board6Port1Color;
    IBOutlet NSTextField* Board6Port2Color;
    IBOutlet NSTextField* Board6Port3Color;
    IBOutlet NSTextField* Board6Port4Color;
    IBOutlet NSTextField* Board6Port5Color;
    IBOutlet NSTextField* Board6Port6Color;
    IBOutlet NSTextField* Board6Port7Color;
    IBOutlet NSTextField* Board6Port8Color;
    IBOutlet NSTextField* Board7Port1Color;
    IBOutlet NSTextField* Board7Port2Color;
    IBOutlet NSTextField* Board7Port3Color;
    IBOutlet NSTextField* Board7Port4Color;
    IBOutlet NSTextField* Board7Port5Color;
    IBOutlet NSTextField* Board7Port6Color;
    IBOutlet NSTextField* Board7Port7Color;
    IBOutlet NSTextField* Board7Port8Color;
    IBOutlet NSTextField* Board8Port1Color;
    IBOutlet NSTextField* Board8Port2Color;
    IBOutlet NSTextField* Board8Port3Color;
    IBOutlet NSTextField* Board8Port4Color;
    IBOutlet NSTextField* Board8Port5Color;
    IBOutlet NSTextField* Board8Port6Color;
    IBOutlet NSTextField* Board8Port7Color;
    IBOutlet NSTextField* Board8Port8Color;
    IBOutlet NSTextField* Board9Port1Color;
    IBOutlet NSTextField* Board9Port2Color;
    IBOutlet NSTextField* Board9Port3Color;
    IBOutlet NSTextField* Board9Port4Color;
    IBOutlet NSTextField* Board9Port5Color;
    IBOutlet NSTextField* Board9Port6Color;
    IBOutlet NSTextField* Board9Port7Color;
    IBOutlet NSTextField* Board9Port8Color;
    IBOutlet NSTextField* Board10Port1Color;
    IBOutlet NSTextField* Board10Port2Color;
    IBOutlet NSTextField* Board10Port3Color;
    IBOutlet NSTextField* Board10Port4Color;
    IBOutlet NSTextField* Board10Port5Color;
    IBOutlet NSTextField* Board10Port6Color;
    IBOutlet NSTextField* Board10Port7Color;
    IBOutlet NSTextField* Board10Port8Color;
    IBOutlet NSTextField* Board11Port1Color;
    IBOutlet NSTextField* Board11Port2Color;
    IBOutlet NSTextField* Board11Port3Color;
    IBOutlet NSTextField* Board11Port4Color;
    IBOutlet NSTextField* Board11Port5Color;
    IBOutlet NSTextField* Board11Port6Color;
    IBOutlet NSTextField* Board11Port7Color;
    IBOutlet NSTextField* Board11Port8Color;
    IBOutlet NSTextField* Board12Port1Color;
    IBOutlet NSTextField* Board12Port2Color;
    IBOutlet NSTextField* Board12Port3Color;
    IBOutlet NSTextField* Board12Port4Color;
    IBOutlet NSTextField* Board12Port5Color;
    IBOutlet NSTextField* Board12Port6Color;
    IBOutlet NSTextField* Board12Port7Color;
    IBOutlet NSTextField* Board12Port8Color;
    IBOutlet NSTextField* Board13Port1Color;
    IBOutlet NSTextField* Board13Port2Color;
    IBOutlet NSTextField* Board13Port3Color;
    IBOutlet NSTextField* Board13Port4Color;
    IBOutlet NSTextField* Board13Port5Color;
    IBOutlet NSTextField* Board13Port6Color;
    IBOutlet NSTextField* Board13Port7Color;
    IBOutlet NSTextField* Board13Port8Color;
    IBOutlet NSTextField* Board14Port1Color;
    IBOutlet NSTextField* Board14Port2Color;
    IBOutlet NSTextField* Board14Port3Color;
    IBOutlet NSTextField* Board14Port4Color;
    IBOutlet NSTextField* Board14Port5Color;
    IBOutlet NSTextField* Board14Port6Color;
    IBOutlet NSTextField* Board14Port7Color;
    IBOutlet NSTextField* Board14Port8Color;
    IBOutlet NSTextField* Board15Port1Color;
    IBOutlet NSTextField* Board15Port2Color;
    IBOutlet NSTextField* Board15Port3Color;
    IBOutlet NSTextField* Board15Port4Color;
    IBOutlet NSTextField* Board15Port5Color;
    IBOutlet NSTextField* Board15Port6Color;
    IBOutlet NSTextField* Board15Port7Color;
    IBOutlet NSTextField* Board15Port8Color;
    IBOutlet NSTextField* Board16Port1Color;
    IBOutlet NSTextField* Board16Port2Color;
    IBOutlet NSTextField* Board16Port3Color;
    IBOutlet NSTextField* Board16Port4Color;
    IBOutlet NSTextField* Board16Port5Color;
    IBOutlet NSTextField* Board16Port6Color;
    IBOutlet NSTextField* Board16Port7Color;
    IBOutlet NSTextField* Board16Port8Color;
}
@property (assign) IBOutlet NSWindow *window;
@property (nonatomic, retain) IBOutlet NSTextField* PortName1;
@property (nonatomic, retain) IBOutlet NSTextField* PortName2;
@property (nonatomic, retain) IBOutlet NSTextField* PortName3;
@property (nonatomic, retain) IBOutlet NSTextField* PortName4;
@property (nonatomic, retain) IBOutlet NSTextField* PortName5;
@property (nonatomic, retain) IBOutlet NSTextField* PortName6;
@property (nonatomic, retain) IBOutlet NSTextField* PortName7;
@property (nonatomic, retain) IBOutlet NSTextField* PortName8;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity1;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity2;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity3;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity4;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity5;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity6;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity7;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity8;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity9;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity10;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity11;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity12;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity13;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity14;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity15;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity16;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity17;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity18;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity19;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity20;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity21;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity22;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity23;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity24;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity25;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity26;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity27;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity28;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity29;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity30;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity31;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity32;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity33;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity34;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity35;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity36;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity37;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity38;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity39;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity40;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity41;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity42;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity43;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity44;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity45;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity46;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity47;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity48;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity49;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity50;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity51;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity52;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity53;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity54;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity55;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity56;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity57;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity58;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity59;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity60;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity61;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity62;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity63;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity64;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity65;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity66;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity67;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity68;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity69;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity70;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity71;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity72;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity73;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity74;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity75;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity76;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity77;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity78;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity79;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity80;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity81;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity82;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity83;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity84;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity85;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity86;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity87;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity88;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity89;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity90;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity91;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity92;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity93;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity94;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity95;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity96;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity97;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity98;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity99;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity100;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity101;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity102;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity103;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity104;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity105;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity106;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity107;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity108;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity109;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity110;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity111;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity112;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity113;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity114;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity115;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity116;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity117;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity118;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity119;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity120;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity121;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity122;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity123;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity124;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity125;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity126;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity127;
@property (nonatomic, retain) IBOutlet NSTextField* Electricity128;
- (NSMutableArray*)ScanPort;
- (IBAction)Start:(id)sender;
- (IBAction)Stop:(id)sender;
- (IBAction)Refresh:(id)sender;
@end
